/* 0.8 review UI. Same public preview; no accounts, GPS, push, or paid services. */
(()=>{'use strict';
const $=id=>document.getElementById(id), E=(tag,text='',cls='')=>{const x=document.createElement(tag);x.textContent=text;x.className=cls;return x;};
const B=(text,fn,cls='sx-button')=>{const b=E('button',text,cls);b.type='button';b.onclick=()=>{try{const r=fn();if(r?.catch)r.catch(error);}catch(e){error(e);}};return b;};
const N={adult:['나루',23,'플리부터 친해질래?','디지코어','공연'],outsider:['유나',21,'답장은 느려도, 노래 취향은 확실해.','제이팝','사진'],owner:['도윤',25,'혼자 가던 공연, 이제 같이 갈래?','인디록','카페'],seo:['서아',22,'밤 산책보다 낮 카페가 좋아.','드림팝','카페'],rio:['리오',24,'이어폰 한쪽을 나눌 사람이 필요해.','하이퍼팝','공연'],ash:['지안',20,'잘 웃는데 슬픈 노래만 들어.','이모팝','필름사진'],sol:['솔',26,'모르는 밴드 얘기부터 시작하자.','얼터너티브','레코드'],eun:['은우',23,'내 플레이리스트에 네 추천 한 곡.','신스팝','산책'],hae:['해원',19,'말보다 음악이 편한 편.','제이팝','그림'],teen:['하루',17,'취향 맞는 친구 구해요.','인디','그림'],younger:['민',14,'같이 그림 그릴 친구.','게임음악','그림'],eighteen:['하늘',18,'공부 끝나면 플레이리스트 공유.','록','게임'],sixteen:['연',16,'음악 얘기할 친구를 찾아요.','제이팝','그림'],fifteen:['보리',15,'게임도 하고 음악도 듣고.','게임음악','게임']};
const me=()=>identity?.userId, info=id=>{const n=N[id];if(!n)return null;return {id,nickname:SAMPLE.settings[id]?.nickname??n[0],age:n[1],bio:SAMPLE.settings[id]?.bio??n[2],region:SAMPLE.settings[id]?.region??'서울 마포구',interests:SAMPLE.settings[id]?.interests??[n[4],'음악','사진','카페','산책'],music:SAMPLE.settings[id]?.music??[n[3],'인디록','제이팝'],active:Boolean(SAMPLE.settings[id]?.status==='active'&&!SAMPLE.deleted.has(id)),visibility:SAMPLE.settings[id]?.visibility??'PRIVATE',dating:DEMO.users[id]?.state.preference?.enabled===true,dmPolicy:SAMPLE.settings[id]?.dmPolicy};};
const name=id=>info(id)?.nickname??'가상 사용자';
function seedMore(){for(const [id,n]of Object.entries(N)){if(!DEMO.users[id]){DEMO.users[id]=copy(OFFLINE_SEED.adult);DEMO.users[id].state={adult:n[1]>=19,datingOpen:true,minimumDatingAge:19,preference:n[1]>=19?{enabled:true,minAge:19,maxAge:99}:null};DEMO.users[id].matches={items:[]};DEMO.users[id].spaces={items:[]};DEMO.users[id].plan={unavailable:true};}if(!SAMPLE.settings[id])SAMPLE.settings[id]={nickname:n[0],bio:n[2],region:'서울 마포구',interests:[n[4],'음악','사진','카페','산책'].filter((x,i,a)=>a.indexOf(x)===i),music:[n[3],'인디록','제이팝'].filter((x,i,a)=>a.indexOf(x)===i),visibility:'EVERYONE',dmPolicy:'REQUEST_ONLY',status:'active',policyVersion:'teum-0.6'};
 const p=SAMPLE.settings[id];p.nickname=n[0];p.bio=n[2];p.music=[...new Set([n[3],'인디록','제이팝'])];while(p.interests.length<5)p.interests.push(['게임','그림','독서'][p.interests.length-3]??'공연');while(p.music.length<3)p.music.push('일렉트로닉');}
 for(const [id,n]of Object.entries(N))if(![...actor.options].some(o=>o.value===id)){const o=E('option',`${n[0]} · ${n[1]}세 · 가상 계정`);o.value=id;actor.append(o);}}
seedMore();
const model=new CoupleReview({user:info,visible:validDisplay,matches:()=>DEMO.matches,likes:()=>DEMO.likes,decisions:()=>DEMO.decisions,blocked:(a,b)=>DEMO.blocks.has([a,b].sort().join(':'))});
const legacyMount=mount, legacyAPI=window.qaRequest;
window.qaRequest=async q=>{const {actor:a,path,method,body={}}=q;
 if(path==='/api/v3/dating/matches'&&method==='GET'){try{return ok({items:model.matches(a).map(m=>({id:m.id,person:info(m.peer)}))});}catch(e){return fail(e.message);}}
 if(path.startsWith('/api/v3/dating/matches/')){try{model.match(a,path.split('/')[5]);}catch(e){return fail(e.message);}}
 if(path==='/api/v3/contacts'&&method==='POST'&&!model.canFind(a,body.targetId,'FRIENDS'))return fail('같은 이용 연령대와 현재 공개 설정을 확인해 주세요.');
 if(path==='/api/v3/account/export'&&body.section==='entries'){const own=model.snapshot(a);return ok({items:[...(notes[a]?[{kind:'privateDiary',text:notes[a]}]:[]),...(own?.plans??[]).filter(x=>x.from===a).map(x=>({...x,kind:'dateProposal'})),...(own?.wishes??[]).filter(x=>x.author===a).map(x=>({...x,kind:'sharedWish'}))],nextAfter:null,offlineOnly:true});}
 const r=await legacyAPI(q);if(r.status===200){if(path==='/lab/reset'){model.clear();notes={};seedMore();}if(path==='/api/v3/account/deletion'){delete notes[a];}model.sweep();}return r;};
let mode='DATE',search='',genre='',dialog=null,revision=0,notes={},dateChat=null,swiping=false;
const root=$('workspace'),head=$('stage-head'),settings=$('settings-dialog');
const fmt=v=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const dateDay=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
function error(e){const text=e?.message??'다시 확인해 주세요.';status.textContent=text;const target=dialog?.querySelector('[role=status]');if(target)target.textContent=text;}
function notice(text){status.textContent=text;}
function close(){dialog?.close();dialog=null;}
function sheet(title,fill){close();const focus=document.activeElement,d=E('dialog','','sx-sheet');d.setAttribute('aria-label',title);const h=E('header'),x=B('×',()=>d.close(),'sx-close');x.setAttribute('aria-label','닫기');h.append(E('h2',title),x);d.append(h);fill(d);const errors=E('p','','sx-error');errors.role='status';d.append(errors);d.onclose=()=>{d.remove();if(dialog===d)dialog=null;if(focus?.isConnected)focus.focus();};document.body.append(d);d.showModal();dialog=d;return d;}
function guard(fn){const a=me(),rev=revision;return ()=>{if(me()!==a||revision!==rev||!info(a)?.active)return;return fn();};}
function go(page){close();settings.close();view=page;mount();window.scrollTo({top:0,behavior:'instant'});}
async function switchTo(id,page='couple'){if(!N[id])return;close();settings.close();actor.value=id;view=page;await signIn();notice(`${name(id)}의 가상 화면이야. 실제 로그인은 아니야.`);}
function title(h,p){const box=E('div','','sx-heading');box.append(E('h1',h),E('p',p));head.append(box);return box;}
function row(...nodes){const d=E('div','','sx-row');d.append(...nodes);return d;}
function section(h,p=''){const d=E('section','','sx-panel');d.append(E('h2',h));if(p)d.append(E('p',p,'sx-muted'));return d;}
function avatar(id){return E('span',name(id).slice(0,1),'sx-avatar');}
function tag(text){return E('span',text,'sx-tag');}
function validDisplay(a,b){const p=info(b);if(p?.visibility==='CONNECTIONS')return DEMO.matches.some(m=>!m.closed&&m.pair.includes(a)&&m.pair.includes(b));if(p?.visibility==='SAME_GROUP_ONLY')return (DEMO.users[a]?.spaces.items??[]).some(s=>(DEMO.users[b]?.spaces.items??[]).some(x=>x.id===s.id));return true;}
function candidates(){const a=me();return Object.keys(N).filter(id=>model.canFind(a,id,mode)&&validDisplay(a,id)&&!DEMO.decisions[`${a}:${mode}:${id}`]&&(!search||[name(id),...info(id).music,...info(id).interests].join(' ').includes(search))&&(!genre||info(id).music.includes(genre)));}
function filters(){sheet('딱 네 취향만',d=>{const label=E('label','닉네임 · 음악 · 취향'),input=E('input');input.value=search;input.placeholder='예: 제이팝, 산책';input.maxLength=50;input.setAttribute('aria-label','사람 검색');label.append(input);const lab=E('label','음악 취향'),s=E('select');s.setAttribute('aria-label','음악 필터');for(const g of ['',...new Set(Object.values(N).map(n=>n[3]))]){const o=E('option',g||'모든 취향');o.value=g;s.append(o);}s.value=genre;lab.append(s);d.append(label,lab,B('이 취향으로 찾기',guard(()=>{search=input.value.trim();genre=s.value;close();mount();}),'sx-primary'),B('필터 초기화',guard(()=>{search='';genre='';close();mount();})));});}
function next(action,p){if(swiping||!info(me())?.active)return;swiping=true;try{const a=me();const result=model.swipe(a,p.id,mode,action);renderDiscover();if(result.matched)sheet('너도, 나도 같은 쪽.',d=>{d.append(row(avatar(a),E('span','♡','sx-heart'),avatar(p.id)),E('p',`${p.nickname}와 서로 좋아요. 매칭이 생겼어.`),E('p','연애 연결은 둘이 확인하고, 위치 공유는 그다음 따로 동의해.','sx-muted'),B('우리 공간에서 연결 확인',()=>go('couple'),'sx-primary'),B('대화부터 시작',()=>openDateChat(result.matchId)));if(p.id==='outsider'&&a==='adult')d.append(E('small','유나는 상대 좋아요가 미리 준비된 가상 매칭 예시야.','sx-fine'));});else notice(action==='pass'?'다음 사람을 보여줄게.':result.friend?'관심을 표시했어. 모임에서 서로 수락하고 대화해 봐.':'좋아요를 보냈어. 상대도 선택하면 매칭돼.');}finally{swiping=false;}}
function bindSwipe(card,p){let start=null,dx=0,dy=0,drag=false,cancelled=false;const reset=()=>{card.style.transform='';card.dataset.direction='';start=null;drag=false;};card.onpointerdown=e=>{if(e.button!==0||e.target.closest('button,a,input,select'))return;start={x:e.clientX,y:e.clientY,id:e.pointerId};dx=dy=0;drag=cancelled=false;};card.onpointermove=e=>{if(!start||e.pointerId!==start.id||cancelled)return;dx=e.clientX-start.x;dy=e.clientY-start.y;if(!drag&&Math.abs(dy)>12&&Math.abs(dy)>Math.abs(dx)){cancelled=true;return;}if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.2)drag=true;if(drag){try{card.setPointerCapture(e.pointerId);}catch{}card.style.transform=`translateX(${dx*.72}px) rotate(${dx/28}deg)`;card.dataset.direction=dx>35?'like':dx< -35?'pass':'';}};card.onpointerup=e=>{if(!start||e.pointerId!==start.id)return;const commit=drag&&!cancelled&&Math.abs(dx)>Math.min(90,card.offsetWidth*.25)&&Math.abs(dx)>Math.abs(dy);const direction=dx>0?'like':'pass';reset();if(commit)next(direction,p);};card.onpointercancel=reset;card.onlostpointercapture=e=>{if(e.target===card&&start)reset();};card.onkeydown=e=>{if(e.target!==card)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();next(e.key==='ArrowRight'?'like':'pass',p);}};}
function detail(p){sheet(`${p.nickname} · ${p.age}`,d=>{d.append(E('p',p.bio),row(...p.interests.map(tag)),E('h3','좋아하는 음악'),E('p',p.music.join(' · ')),E('p',`${p.region} · 가상 프로필 · 정확한 위치는 공개하지 않아.`,'sx-fine'),B(mode==='DATE'?'좋아요 보내기':'친구로 관심 표시',guard(()=>{close();next('like',p);}),'sx-primary'),B('친구 모임에서 만나기',()=>go('groups')),B('신고 · 차단',()=>report(p)));});}
function report(p){sheet('불편한 연결은 멈춰도 돼.',d=>{d.append(E('p',`${p.nickname} · 신고와 차단은 별개야.`));const s=E('select');s.setAttribute('aria-label','신고 이유');for(const label of ['괴롭힘','개인정보','청소년 안전','성적 내용','사기','기타'])s.append(E('option',label));d.append(s,B('샘플 신고 남기기',guard(async()=>{await request('POST','/api/v3/discovery/reports',{targetType:'PROFILE',targetId:p.id,reason:s.value,description:''});close();notice('이 탭에 샘플 신고를 기록했어. 실제 신고 접수는 아니야.');})),B('이 사람 차단하기',guard(async()=>{await request('POST','/api/v3/blocks',{targetId:p.id});model.sweep();close();mount();notice('차단했어. 커플 연결과 공유 위치도 닫았어.');}),'sx-danger'));});}
function renderDiscover(){app?.destroy();app=null;root.className='sx-discovery';root.replaceChildren();head.replaceChildren();if(info(me()).age<19)mode='FRIENDS';const h=title('너랑, 같은 쪽.','스와이프로 찾고, 서로 좋아하면 연결돼.');const controls=row();if(info(me()).age>=19)for(const [label,key]of [['연애 19+','DATE'],['친구','FRIENDS']]){const b=B(label,()=>{mode=key;renderDiscover();});b.setAttribute('aria-pressed',String(mode===key));controls.append(b);}else controls.append(tag('또래 친구만'));controls.append(B('필터',filters,'sx-text'));h.append(controls);
 const ids=candidates();if(!ids.length){const empty=section(model.current(me())?.phase==='active'&&mode==='DATE'?'이미 우리 사이가 있네.':'오늘의 카드는 여기까지.','친구를 찾거나 취향 모임에서 먼저 이야기해 봐.');empty.append(B('우리 공간 보기',()=>go('couple'),'sx-primary'),B('필터 바꾸기',filters),B('모임 둘러보기',()=>go('groups')));root.append(empty);return;}
 const p=info(ids[0]),stage=E('div','','sx-stage'),card=E('article','','sx-card');card.tabIndex=0;card.setAttribute('aria-label',`${p.nickname} ${p.age}세 프로필. 오른쪽 좋아요, 왼쪽 넘기기`);card.dataset.profile=p.id;const idx=Object.keys(N).indexOf(p.id);card.dataset.tone=String(idx%4);const visual=E('div','','sx-visual'),photo=SAMPLE.photos.find(x=>x.user_id===p.id&&x.status==='approved');if(photo||p.id==='outsider'){const img=E('img');img.src=photo?'data:image/jpeg;base64,'+photo.base64:'portrait.webp';img.alt=photo?'승인된 가상 계정의 샘플 사진':'유나의 가상 프로필 이미지';img.draggable=false;visual.append(img);}else{visual.append(E('span',p.nickname.slice(0,1),'sx-initial'),E('span','SAME SONG / DIFFERENT US','sx-record-text'));}const upper=row(tag(`${mode==='DATE'?'연애':'친구'} · 가상 프로필`),B('···',()=>detail(p),'sx-more'));const like=E('span','좋아 ♡','sx-stamp sx-like'),pass=E('span','다음 ↗','sx-stamp sx-pass');const text=E('div','','sx-card-info');text.append(E('small',p.music[0],'sx-vibe'),E('h2',`${p.nickname}, ${p.age}`),E('p',p.bio),row(...p.interests.slice(0,3).map(tag)),E('small',p.region+' · 위치 비공개','sx-area'));card.append(visual,upper,like,pass,text);bindSwipe(card,p);stage.append(card);root.append(stage);
 const actions=row();actions.classList.add('sx-swipe-actions');const undo=B('↶',()=>{model.undo(me());renderDiscover();},'sx-undo');undo.setAttribute('aria-label','방금 넘긴 카드 되돌리기');undo.disabled=!model.skips.has(me());const no=B('×',()=>next('pass',p),'sx-no'),yes=B('♡',()=>next('like',p),'sx-yes');no.setAttribute('aria-label','다음 사람으로 넘기기');yes.setAttribute('aria-label',mode==='DATE'?'좋아요 보내기':'친구로 관심 표시');actions.append(undo,no,yes);root.append(actions,E('p',`← 넘기기 · 좋아요 →  /  가상 카드 ${ids.length}개`,'sx-hint'),row(B('모임 둘러보기',()=>go('groups'),'sx-text'),B('내 매칭 보기',()=>go('couple'),'sx-text')));
}
function matchList(){const list=model.matches(me());const panel=section('서로 선택한 사람','연애 매칭과 친구 대화는 분리돼 있어.');if(!list.length)panel.append(E('p','서로 좋아요하면 여기에 나타나.','sx-muted'),B('사람 스와이프하기',()=>go('discover'),'sx-primary'));for(const m of list){const box=E('article','','sx-match-row');box.append(avatar(m.peer),E('strong',name(m.peer)),B('대화',()=>openDateChat(m.id),'sx-text'));if(!model.current(me()))box.append(B('커플 확인',guard(()=>{model.request(me(),m.id);go('couple');})));panel.append(box);}return panel;}
function ours(){root.className='sx-ours';const a=me(),r=model.snapshot(a);title('우리, 여기서부터.','매칭한 두 사람의 공간. 위치는 별도로 동의해.');if(info(a).age<19){const p=section('또래와 취향부터.','청소년 가상 계정은 친구·모임·대화를 체험할 수 있어. 성인 커플 기능은 열리지 않아.');p.append(B('친구 스와이프',()=>{mode='FRIENDS';go('discover');},'sx-primary'),B('모임과 장소 투표',()=>go('groups')));root.append(p,diaryEntry());return;}
 if(!r){root.append(matchList(),diaryEntry());return;}
 if(r.phase==='pending'){const p=section(`${name(r.from)} ♡ ${name(r.to)}`,'서로 좋아요한 뒤, 연애 연결을 둘이 확인하는 단계야. 위치는 아직 꺼져 있어.');if(a===r.to)p.append(B('우리 연애 연결 확인',guard(()=>{model.accept(a,r.id);mount();}),'sx-primary'));else p.append(E('p','상대의 확인을 기다리는 중','sx-status'),B('상대 가상 화면으로 확인',()=>switchTo(r.to),'sx-primary'));p.append(B('이 연결 종료',()=>endDialog(r)));root.append(p,diaryEntry());return;}
 const hero=section(`${name(a)} ♡ ${name(r.peer)}`);hero.classList.add('sx-couple-hero');const count=r.anniversary?Math.floor((Date.parse(dateDay(Date.now()))-Date.parse(r.anniversary))/86400000)+1:null;hero.append(E('strong',count?`함께한 지 ${count}일`:'우리의 첫 페이지','sx-day'),E('p','두 사람 모두 확인한 연애 연결','sx-fine'),row(B('대화하기',()=>openDateChat(r.matchId),'sx-primary'),B('상대 화면',()=>switchTo(r.peer))),B('연결 종료 · 차단',()=>endDialog(r),'sx-text'));root.append(hero);
 const location=section('지금, 어디쯤이야?','서로 동의한 1시간만. 실제 위치가 아닌 예시야.');location.dataset.section='location';const s=r.sharing;if(!s){location.append(E('div','위치 공유 OFF','sx-status'),B('1시간 위치 공유 요청',guard(()=>{model.requestSharing(a,r.id);mount();}),'sx-primary'));}
 else if(s.phase==='pending'){location.append(E('div','양쪽 동의 대기 · 위치 비공개','sx-status'));if(s.to===a)location.append(B('위치 공유에 동의',guard(()=>{model.acceptSharing(a,r.id);mount();}),'sx-primary'));else location.append(B('상대 가상 화면에서 동의',()=>switchTo(s.to)));location.append(B('요청 취소 · 거절',guard(()=>{model.stopSharing(a,r.id);mount();}),'sx-text'));}
 else{location.append(E('div','공유 중 · '+Math.max(0,Math.ceil((s.until-Date.now())/60000))+'분 남음','sx-status'));const map=E('div','','sx-map');map.setAttribute('aria-label','가상 위치 배치도. 실제 지도 아님');map.append(E('span','예시 위치 · 실제 GPS 아님','sx-map-caption'));for(const id of [a,r.peer]){const p=s.points[id];if(p){const mark=E('span',`${id===a?'나':name(id)} · ${p.label}`,'sx-map-marker');mark.style.left=p.x+'%';mark.style.top=p.y+'%';map.append(mark);}}location.append(map);for(const id of [a,r.peer]){const p=s.points[id];location.append(E('p',`${id===a?'나':name(id)}: ${p?p.label+' · '+(Date.now()-p.at>300000?'갱신 지연':Math.floor((Date.now()-p.at)/60000)+'분 전'):'아직 공유한 예시 위치 없음'}`,'sx-fine'));}const km=model.distance(a,r.id);location.append(E('p',km===null?'둘 다 예시 위치를 갱신하면 거리가 표시돼.':`예시 거리 약 ${km}km · 실거리가 아니야.`,'sx-fine'));const choices=row();for(const p of REVIEW_PLACES)choices.append(B(p.label,guard(()=>{model.locate(a,r.id,p.id);mount();})));location.append(E('p','내 예시 위치 갱신','sx-fine'),choices,B('위치 공유 즉시 끄기',guard(()=>{model.stopSharing(a,r.id);mount();}),'sx-danger'));}root.append(location);
 const mood=section('오늘 마음도, 한 번만.','내가 선택한 기분만 상대에게 보여. 자정이 지나면 지워.');mood.append(E('p',`${name(r.peer)}: ${r.mood[r.peer]??'아직 공유하지 않았어'}`,'sx-note'));const feelings=row();for(const v of ['대화하고 싶어','혼자 쉬고 싶어','그냥 그래','보고 싶어','기분 좋아']){const b=B(v,guard(()=>{model.mood(a,r.id,v);mount();}));b.setAttribute('aria-pressed',String(r.mood[a]===v));feelings.append(b);}mood.append(feelings);if(r.mood[a])mood.append(B('내 기분 공유 지우기',guard(()=>{model.withdrawMood(a,r.id);mount();}),'sx-text'));root.append(mood);
 const plans=section('다음엔, 같이 가자.');for(const p of r.plans.filter(p=>p.state!=='cancelled')){const item=E('article','','sx-plan');item.append(E('strong',p.place),E('p',fmt(p.when)),E('small',p.state==='confirmed'?'둘이 확정한 약속':'상대 수락 대기'));if(p.state==='pending'&&p.to===a)item.append(B('약속 수락',guard(()=>{model.confirmDate(a,r.id,p.id);mount();})));item.append(B('약속 취소',guard(()=>{model.cancelDate(a,r.id,p.id);mount();}),'sx-text'));plans.append(item);}plans.append(B('데이트 약속 제안',()=>dateForm(r),'sx-primary'));root.append(plans);
 const extras=E('details','','sx-details');extras.append(E('summary','기념일 · 같이 하고 싶은 일'));const anniversary=section('우리 시작한 날');if(r.anniversaryProposal){anniversary.append(E('p',r.anniversaryProposal.value+' · 날짜 확인 대기'));if(r.anniversaryProposal.to===a)anniversary.append(B('시작일 확인',guard(()=>{model.confirmAnniversary(a,r.id);mount();})));}anniversary.append(B('시작일 정하기',()=>sheet('우리 시작한 날',d=>{const input=E('input');input.type='date';input.max=dateDay(Date.now());input.value=r.anniversary??dateDay(Date.now());input.setAttribute('aria-label','연애 시작일');d.append(input,E('p','상대도 확인하면 디데이에 반영돼.','sx-fine'),B('시작일 제안',guard(()=>{model.proposeAnniversary(a,r.id,input.value);close();mount();}),'sx-primary'));})));extras.append(anniversary);
 const wishes=section('같이 하고 싶은 일');for(const w of r.wishes){const line=row(B(w.done?'☑':'☐',guard(()=>{model.toggleWish(a,r.id,w.id);mount();}),'sx-text'),E('span',w.text),B('삭제',guard(()=>{model.removeWish(a,r.id,w.id);mount();}),'sx-text'));line.firstChild.setAttribute('aria-label',w.text+' 완료 상태 변경');wishes.append(line);}const input=E('input');input.placeholder='예: 첫 공연 같이 가기';input.maxLength=80;input.setAttribute('aria-label','함께 하고 싶은 일');wishes.append(input,B('목록에 추가',guard(()=>{model.wish(a,r.id,input.value);mount();})));extras.append(wishes);root.append(extras,diaryEntry());}
function endDialog(r){sheet('우리 연결을 종료할까?',d=>{d.append(E('p','공유 위치와 함께 쓰던 약속·기념일·기분 기록을 닫고 기존 매칭도 종료해. 상대의 동의 없이도 종료할 수 있어.'),B('연애 연결 종료',guard(()=>{model.end(me(),r.id);close();mount();}),'sx-danger'),B('신고 · 차단으로 이동',()=>report(info(r.peer??(r.from===me()?r.to:r.from)))));});}
function dateForm(r){sheet('같이 갈 약속',d=>{const place=E('select');place.setAttribute('aria-label','데이트 장소');for(const p of REVIEW_PLACES.filter(p=>p.id!=='home')){const o=E('option',p.label+' · 가상 장소');o.value=p.id;place.append(o);}const time=E('input');time.type='datetime-local';time.setAttribute('aria-label','데이트 일시');const tomorrow=new Date(Date.now()+86400000+9*3600000).toISOString().slice(0,10);time.value=tomorrow+'T14:00';const label=E('label','한국시간');label.append(time);d.append(place,label,B('약속 제안하기',guard(()=>{model.proposeDate(me(),r.id,place.value,time.value+':00+09:00');close();mount();}),'sx-primary'));});}
function diaryEntry(){const b=B('',()=>go('diary'),'sx-diary');b.append(E('strong','내 마음은, 내 일기에.'),E('small','공유하지 않는 나의 한 줄 일기'));return b;}
function diary(){title('오늘은 여기까지.','이 탭 안의 가상 계정별 메모야. 새로고침하면 사라져.');const a=me(),t=E('textarea');t.maxLength=1000;t.rows=8;t.value=notes[a]??'';t.placeholder='사실 오늘 내 마음은…';t.setAttribute('aria-label','나만의 일기');const count=E('p',`${t.value.length}/1000`,'sx-fine');t.oninput=()=>{count.textContent=`${t.value.length}/1000`;};root.append(t,count,B('내 일기에 남기기',guard(()=>{notes[a]=t.value;notice('이 탭의 내 일기에 남겼어.');}),'sx-primary'),B('내 일기 삭제',()=>sheet('내 일기를 지울까?',d=>d.append(B('일기 삭제 확인',guard(()=>{delete notes[a];close();mount();}),'sx-danger')))));}
function openDateChat(id){model.match(me(),id);go('matches');dateChat=id;queueMicrotask(()=>{if(!app||view!=='matches')return;const m=model.matches(me()).find(m=>m.id===id);if(m)void app.openChat({id,person:info(m.peer)});});}
function inbox(){sheet('내 소식',d=>{const rows=model.inbox(me());if(!rows.length)d.append(E('p','새로운 소식이 없어.'));for(const n of rows){const p=section(n.text);p.append(E('small',fmt(n.at),'sx-fine'));d.append(p);}model.readInbox(me());d.append(B('우리 공간 열기',()=>go('couple'),'sx-primary'));});}
function compactAccount(){if(view!=='account')return;const form=root.querySelector('form.aw-section');if(form&&!form.dataset.compact){form.dataset.compact='1';const labels=[...form.children].filter(n=>n.tagName==='LABEL'),more=E('details','','sx-details');more.append(E('summary','취향 · 공개 범위 설정'));for(const l of labels.slice(2))more.append(l);form.insertBefore(more,form.querySelector('button[type=submit]'));}}
new MutationObserver(compactAccount).observe(root,{subtree:true,childList:true});
mount=function(){if(!identity)return;++revision;close();app?.destroy();app=null;head.replaceChildren();root.replaceChildren();root.className='';status.textContent='';$('reset').disabled=false;if(!info(me())?.active)view='account';document.body.dataset.page=view;for(const b of $('main-nav').children){const selected=b.dataset.page===(view==='discover'?'discover':['friends','matches'].includes(view)?'friends':'couple');b.toggleAttribute('aria-current',selected);if(selected)b.setAttribute('aria-current','page');}
 if(view==='discover')renderDiscover();else if(view==='couple')ours();else if(view==='diary')diary();else if(view==='groups'){title('오늘, 혼자 말고.','같은 취향으로 모이고, 공개 장소에서 만나.').append(B('모임 장소 · 시간 투표',()=>go('plans'),'sx-primary'));legacyMount();}else if(view==='friends'){const h=title('말 걸어도 괜찮아.','친구 요청을 수락한 대화만 시작돼.');if(info(me())?.age>=19)h.append(B('연애 매칭 대화 보기',()=>go('matches')));legacyMount();}else if(view==='plans'||view==='matches'){title(view==='plans'?'약속도, 우리답게.':'서로 마음이 닿았어.','가상 계정의 기록만 표시해.');const saved=view;view='discover';legacyMount();view=saved;app.tab=saved==='plans'?'plans':'matches';void app.reload();}else{title('나의 작은 세계','프로필 · 사진 · 개인정보 관리');view='account';legacyMount();app.options.onBack=()=>go('discover');}compactAccount();const rs=model.snapshot(me());phase=[rs?.id,rs?.phase,rs?.sharing?.phase,rs?.sharing?.until].join(':');};
$('brand-home').onclick=()=>go('discover');$('inbox-open').onclick=inbox;for(const b of $('main-nav').children)b.onclick=()=>go(b.dataset.page);
$('settings-open').onclick=()=>{close();$('current-person').textContent=name(me())+' · 가상 계정';$('settings-links').replaceChildren(B('프로필 · 사진',()=>go('account')),B('나만의 일기',()=>go('diary')),B('모임 · 장소 투표',()=>go('groups')));settings.showModal();};$('settings-close').onclick=()=>settings.close();settings.onclose=()=>$('settings-open').focus();
$('reset').onclick=async()=>{await request('POST','/lab/reset',{});view='discover';mode='DATE';search='';genre='';settings.close();mount();notice('현재 탭의 샘플만 초기화했어.');};actor.addEventListener('change',()=>{close();settings.close();mode='DATE';search='';genre='';view='discover';});
let phase='';const timer=setInterval(()=>{if(!identity)return;const s=model.snapshot(me());const next=[s?.id,s?.phase,s?.sharing?.phase,s?.sharing?.until].join(':');if(next!==phase&&view==='couple'&&!dialog){phase=next;mount();}},1000);
window.addEventListener('pagehide',()=>{clearInterval(timer);model.clear();notes={};close();});window.addEventListener('pageshow',e=>{if(e.persisted)go('discover');});
window.MENHERA_REVIEW={version:'0.8.0',realGPS:false,realPush:false,realMembers:false,ads:false};
// Test seam exposes this same synthetic model, never credentials or production state.
window.REVIEW08={model,info,go,switchTo,candidates};view='discover';if(identity)mount();
})();
